function results = FlowerFilter(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
 [~,RGBB] = FlowerBackgroundFilter(im);
  [~,RGBW] = WhiteColorAdder(im);
  [~,RGBP] = PurpleFlower(im);
  [~,RGBO] = OrangeFlower(im);
  RGB=max(RGBB,RGBW);                  %(RGBB,RGBW,RGBP,RGBO);
  RGB=max(RGB,RGBP);
  RGB=max(RGB,RGBO);

results.RGB =RGB;


%--------------------------------------------------------------------------
